name: dvgs

channels: 
  - conda-forge
  - pytorch
  - nvidia
  
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - h5py
  - pytorch::pytorch=1.13
  - nvidia::pytorch-cuda=11.7
  - torchvision
  - ipykernel
  - umap-learn
  - statsmodels
  - pip
  - pip:
    - tensorboard